package model.enums;

/**
 * Describes the name of the territory in the map.
 * @author dallem@usi.ch
 */
public enum TerritoryName {
    ALASKA,
    NORTH_WEST_TERRITORY,
    ALBERTA,
    ONTARIO,
    QUEBEC,
    GREENLAND,
    CENTRAL_AMERICA,
    WESTERN_UNITED_STATES,
    EASTERN_UNITED_STATES,
    VENEZUELA,
    BRAZIL,
    PERU,
    ARGENTINA,
    ICELAND,
    GREAT_BRITAIN,
    WESTERN_EUROPE,
    SOUTHERN_EUROPE,
    NORTHERN_EUROPE,
    SCANDINAVIA,
    UKRAINE,
    URAL,
    SIBERIA,
    AFGHANISTAN,
    CHINA,
    INDIA,
    IRKUTSK,
    JAPAN,
    KAMCHATKA,
    MIDDLE_EAST,
    MONGOLIA,
    SIAM,
    YAKUTSK,
    NORTH_AFRICA,
    EGYPT,
    CONGO,
    EAST_AFRICA,
    SOUTH_AFRICA,
    MADAGASCAR,
    EASTERN_AUSTRALIA,
    INDONESIA,
    NEW_GUINEA,
    WESTERN_AUSTRALIA,
    NONE
}
